# Site settings
title: Alexander Samsig
twitter_username: Asamsig
name: Alexander Samsig
location: Trondheim, Norway
picture: https://avatars0.githubusercontent.com/u/2983219?s=460&v=4

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/Asamsig
 - title: StackOverflow
   url: https://stackoverflow.com/users/1882855/asamsig
 - title: LinkedIn
   url: https://www.linkedin.com/in/alexander-samsig/

#Any buzzword skills you want to include
skills:
 - Scala
 - Playframework
 - Slick
 - Akka
 - Java
 - SQL
 - REST
 - RabbitMQ
 - Technical Architecture

#Work experience is required
roles:
 - title: Consul&shy;tant
   start: 2018
   employer: EVRY AS
   description:
 - title: Software Developer
   start: 2015
   end: 2018
   employer: WTW AS
   description: Full stack development in Scala, with use of Java interop where necessary. Using technologies such as Play Framework, Akka, Slick, Op-Rabbit, Specs2, SBT.
     <br><br>
     Deploying applications to the cloud using AWS.
     <br><br>
     Some maintenance and further development of PHP.

#Education is required
education:
 - level: Bachelor in Sofware Develop&shy;ment
   date: 2015
   subject: Computer Science
   school: Copenhagen Business Academy

#This section is optional (as is the image link below)
certifications:
   profileurl: https://www.youracclaim.com/users/alexander-samsig
   courses:
    - title: Principles of Reactive Architecture
      link: https://www.youracclaim.com/badges/866c5bf5-b517-4198-8a15-d96c3e978131/
      optionalimage: https://images.youracclaim.com/images/c37082a5-c2dc-41a3-b3ff-9e4b33bb746f/Princ%2Bof%2Breact%2Barch%2Bv1.png
      imagesize: 110
      date: December 15, 2018
    - title: Scala Programming for Data Science - Level 2
      link: https://www.youracclaim.com/badges/3c04c946-cbb7-4253-974f-874ed5566070
      optionalimage: https://images.youracclaim.com/images/29e051f5-d33a-45ea-b5c3-64156561c614/Scala%2BPgrm%2Bfor%2BData%2BSci%2BLevel%2B2%2B-%2BCC.png
      imagesize: 110
      date: July 27, 2017
    - title: Scala Programming for Data Science - Level 1
      link: https://www.youracclaim.com/badges/8d469fe6-0a72-4757-8be1-1cd3198e2c19
      optionalimage: https://images.youracclaim.com/images/cb0a29a2-a96f-485f-92ad-0dee9da015db/Scala%2BPgrm%2Bfor%2BData%2BSci%2BLevel%2B1%2B-%2BCC.png
      imagesize: 110
      date: July 02, 2017

#List of interesting Github repo/projects to include - optional
github:
 - Asamsig/playwithslickcodegen
 - Asamsig/play-with-scalajs-example
 - Asamsig/scalajs-type-provision-demo
 - Asamsig/Scala.JS-Electron-WeatherApp

#Stackoverflow flair is optional
#stackoverflow:
#   profileurl: https://stackoverflow.com/users/1882855/asamsig
#   flairimageurl: https://stackoverflow.com/users/flair/1882855.png

intro: |
  I'm a tech enthusiast, I spend a lot time learning, reading and going to meetups about new technologies, also those out of my specific area.
  <br>
  <br>
  Currently Scala is my go to language, but I've previously worked with C#, Java, Android, PHP, and web development and all that comes with that.
  <br>
  <br>
  Since being introduced with Scala I've set my sights on things such as fast reactive systems, and Big Data processing.
  <br>
  <br>
  Currently my fascination is around Scala.JS and Akka (reactive streams).